# Generated by Django 5.2.4 on 2025-08-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Comment author"),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="Post body"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.PositiveIntegerField(default=0, verbose_name="Post rating"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Tag name"),
        ),
    ]
